controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    difrobot_controller:
      type: diff_drive_controller/DiffDriveController
simple_velocity_controller:
  ros__parameters:
    joints: [wheel_left_joint, wheel_right_joint]
difrobot_controller:
  ros__parameters:
    left_wheel_names: [wheel_left_joint]
    right_wheel_names: [wheel_right_joint]
    wheel_separation: 0.17
    wheel_radius: 0.033
    base_frame_id: base_footprint
    odom_frame_id: odom
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    enable_odom_tf: true
